### ISSUE TITLE
Determining number of CPUs for queries and iterators

### ISSUE THREAD

**Issue by vadim** [MatteoLacki/timspy#5]
Using `timsPy` to make queries on a 40-core machine, I notice that the python interpreter usage spikes to 2000+% CPU. How is the maximal number of threads set? I've been unable to find references to OpenMP in the code.

**Comment by MatteoLacki** [comment]
Hello Vadim,

I think it might be because of the opentims_bruker_bridge which is basically Bruker's code for doing transformations between TOF and MZ and scan an inverse ion mobility. We are dealing with that part right now, especially that Michal has written a nice new multithreaded version of the code and is trying to turn them off too. 

We will stay in touch,

Best,

**Comment by vadim** [comment]
Thank you so much for your reply, @MatteoLacki, appreciate it! That's what I suspected as well. Look forward to hearing more of your progress. The project is fantastic, and it's great to hear that Bruker is supporting you guys.

**Comment by michalsta** [comment]
Hi,

The aforementioned code for setting the number of threads is finished, so if you want to be our beta teste^H^H^H^H^H early adopter, you can grab opentims v1.0.9a2 (or master branch on github) and call opentims.set_num_threads(...)

Note: it's in opentims, not timspy - timspy just uses opentims under the hood.
